# Generated by Django 4.2 on 2023-04-24 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='date_off',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='news',
            name='rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='news',
            name='text',
            field=models.TextField(null=True),
        ),
    ]
